- .github/workflows/pull_request.yml
- src/lib/components/Button.svelte
Jira ticket: [LDAF-155](https://ldaf.atlassian.net/browse/LDAF-155)
- Adds a very barebones workflow to execute `npm run lint` and `npm run test:unit` on PR creation/updates
None
<!-- If you plan on leaving a self-review, note that here. >
[LDAF-155]: https://ldaf.atlassian.net/browse/LDAF-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LDAF-155: Add GitHub Action workflow for pull requests

- src/lib/components/landingPage/Banner.svelte
> Banner: remove console.log statement

- .storybook/preview.ts
- Imports `src/app.scss` in `.storybook/preview.ts`
> Make Storybook preview import global app styles

- src/lib/components/Header/Header.svelte
- src/lib/components/Search/Search.svelte
- src/lib/components/Search/Search.test.ts
- src/lib/components/Search/index.ts
- src/lib/components/Search/options.ts
- src/stories/Search.stories.ts
Jira tickets: [LDAF-228](https://ldaf.atlassian.net/browse/LDAF-228), [LDAF-229](https://ldaf.atlassian.net/browse/LDAF-229)
- Adds a `Search` component
- Uses the `Search` component for the search bar in the header
[LDAF-228]: https://ldaf.atlassian.net/browse/LDAF-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LDAF-229]: https://ldaf.atlassian.net/browse/LDAF-229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Svelte search component

- .github/workflows/tests_and_reports.yml
- .gitignore
- package-lock.json
- package.json
- src/routes/.build-info/+page.svelte
~This is based on #68.~
- Adds bundle visualizer to the meta-site
N/A, this is purely a CI change.
> Add bundle visualizer to meta-site

- vite-plugin-blurhash/readme.md
- Adds readme to `vite-plugin-blurhash`
> Add readme.md to vite-plugin-blurhash

- vite-plugin-import-as-bundle-string/readme.md
- Adds readme to `vite-plugin-import-as-bundle-string`
> Add readme to vite-plugin-import-as-bundle-string

- vite-plugin-ldaf-icon/readme.md
- Add readme to `vite-plugin-ldaf-icon`
> Add readme to vite-plugin-ldaf-icon

- docs/decisions/image-providers.md
Jira ticket: [LDAF-269](https://ldaf.atlassian.net/browse/LDAF-269)
Adds a decision doc for the image API providers
[LDAF-269]: https://ldaf.atlassian.net/browse/LDAF-269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Decision Doc: Image Providers

- .prettierignore
- codegen.yml
- package-lock.json
- package.json
- src/lib/services/contentful/schema.graphql
- src/lib/services/contentful/schema.ts
Depends on #132.
- Generates the GraphQL schema in addition to the TypeScript schema
- Updates both schemas
> Generate GraphQL schema

- src/lib/components/ContentfulRichText/nodes/EntryHyperlink.svelte
- Fixes a bug in the `EntryHyperlink` component.
> fix EntryHyperlink

- src/lib/components/Footer/Footer.svelte
Fixing these for now; they'll be in Contentful eventually.
> Fix hardcoded footer links

- src/lib/components/ContentfulRichText/ContentfulRichText.svelte
Closes #376.
- Add an object identity key to `ContentfulRichText` so it re-renders if the document changes. In the future it'd be better to have an ID based on the content itself, but we need to investigate how this would affect performance.
> Fix content consistency issue

- src/routes/+page.svelte
This allows the YouTube video in the homepage test content to show up.
> Show youtube video in test content

- src/routes/licensing-permits/+page.svelte
Qucik update per @uxrebecca's [request in Slack](https://adhoc.slack.com/archives/C04EYUA76BT/p1692913393129349).
> Add seed dealer licensing to hard-coded "Licensing and permits" page.

- src/lib/components/ContentfulRichText/nodes/AssetHyperlink.svelte
- src/lib/components/ContentfulRichText/nodes/EmbeddedAssetBlock.svelte
- src/lib/components/ContentfulRichText/nodes/EmbeddedEntryBlock.svelte
- src/lib/components/Header/Logo/Logo.svelte
- src/routes/(infoPages)/[topTierPage]/+page.svelte
- src/routes/(infoPages)/[topTierPage]/[...serviceGroupPage]/+page.svelte
- src/routes/(infoPages)/about/events/event/[dateAndSlug]/+page.svelte
- src/routes/+page.svelte
Straightforward, simplifying some imports so we use their default export.
> Clean up some Svelte component imports.

- src/lib/components/Card/Card.scss
- src/lib/components/Header/Header.svelte
- src/lib/components/Link/Link.scss
- src/lib/components/ResourceLinks/ResourceLinks.scss
- src/lib/components/ResourceLinks/ResourceLinks.svelte
- src/lib/components/ResourceLinks/index.ts
- src/lib/services/contentful/schema.graphql
- src/lib/services/contentful/schema.ts
- src/routes/+page.server.ts
- src/routes/+page.svelte
- src/routes/__tests__/homePageTestContent.ts
- src/routes/page.scss
- src/stories/ResourceLinks.stories.ts
Jira ticket: [LDAF-395](https://ldaf.atlassian.net/browse/LDAF-395)
- Implements "Popular resources" section on homepage
[LDAF-395]: https://ldaf.atlassian.net/browse/LDAF-395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Implement "Popular resources" section on homepage

- src/routes/(infoPages)/[topTierPage]/[...serviceGroupPage]/+page.server.ts
Jira ticket: [LDAF-429](https://ldaf.atlassian.net/browse/LDAF-429)
This is pretty straightforward; we're already chunking the requests for services (since the query complexity can get quite high with everything that can appear in the service accordion rich text), so we can safely increase the limits on the total amount of references to Service entries and other Core Content pages, as well as the base limit on the separate request for Core Content pages.
**Before**: total of 20 references, allowing up to 20 service entries (split into chunks of 10) and up to 10 core content pages.
**After**: total of 50 references, allowing up to 50 service entries (split into chunks of 10) and up to 50 core content pages.
To test this out, I created a `service-limit-testing` environment in Contentful, …
> [LDAF-429] Increase limits for references to Services and child Core Content pages on Core Content pages

- src/lib/components/ContentfulRichText/nodes/EmbeddedEntryBlock.svelte
- src/lib/components/ContentfulRichText/types.ts
Opening this up as a PR so y'all can leave additional feedback. @Benaiah I'd especially like your eyes on this since (even though it works) I'm not sure if this is the cleanest solution.
> Resolve TS errors for CTAs embedded in rich text fields

- src/lib/components/Footer/Footer.svelte
Megan requested that we update some footer content!
- Change address and non emergency phone number
- Remove TOS link since there's no content
> Update footer addresss and phone number, remove terms of service link

- src/hooks/server/handleCurrentUserAndContentfulClient.ts
- src/lib/components/ContentfulRichText/nodes/Node.svelte
- src/lib/loadPageMetadataMap.ts
- src/lib/services/server/contentful/graphqlClient.ts
- src/lib/services/server/kv/index.ts
- src/routes/logout/+page.server.ts
This shouldn't have any functional impact; just two main changes here:
1. Remove the warnings when we're building the `PageMetadataMap` on production (these logs occur for every request and are not useful).
2. Improve existing error messages so that it's clearer where the errors are originating from (e.g. from Redis vs Contentful vs our application).
> Improve error messages in logs by adding more details.

- src/lib/components/YoutubeSubscribeLink/YoutubeSubscribeLink.scss
- src/lib/services/server/contentful/schema.graphql
- src/lib/services/server/contentful/schema.ts
- src/routes/(infoPages)/[topTierPage]/+page.svelte
- src/routes/(infoPages)/[topTierPage]/[...serviceGroupPage]/+page.server.ts
- src/routes/(infoPages)/[topTierPage]/[...serviceGroupPage]/+page.svelte
- src/routes/(infoPages)/[topTierPage]/[...serviceGroupPage]/__tests__/serviceGroupPageTestContent.ts
- Adds the same video embed that's currently on top tier pages to core content pages. This makes a video embed possible on almost every page, sans News/Events and I think office pages
Video embed on a core content page
To test this out locally, switch your `DEFAULT_CONTENTFUL_ENVIRONMENT` in your `.env.local` config file from `master` to `video-on-all` (I set up this env in Contentful to avoid causing any problems on production).
This is a pretty straightforward rip of the video implementation for the top tier pages
I thought about abstracting the logic to be shared between top tier and core content pages, but that felt a bit premature and makes this addition more removable in the future 
I'm getting weird `code-gen` schema errors again. In this case, it's this:
```
✖ Unable to validate …
```
> Add video embed to core content pages

- src/routes/api/v1/fire-weather/+server.ts
Temporarily adding some logs in the fire data endpoint while troubleshooting with LDAF. We can clean this up to something more streamlined once things are behaving as expected.
> Log fire data as it is getting process

- src/lib/components/ContentfulRichText/nodes/EntryHyperlink.svelte
- src/lib/components/SideNav/SideNav.server.ts
- src/lib/loadEventsNewsMetadataMap.ts
- src/lib/loadPageMetadataMap.ts
- src/lib/util/dates.ts
- src/routes/+layout.svelte
- src/routes/+page.server.ts
- src/routes/api/v1/search-index/+server.ts
- src/routes/api/v1/search-index/status/+server.ts
Keeping the description bare here; this is an attempt to fix up type definitions by utilizing the generated definitions and performing some eldritch TS magic.
> [Issue #578] Iimprove type definitions for search indexing.

- src/routes/(infoPages)/land/fire/safety/fire-danger-map/+page.server.ts
- src/routes/(infoPages)/land/fire/safety/fire-danger-map/+page.svelte
Decided to make this a separate PR to talk through some of these changes in a self-review.
> [No Issue] Improve fetching of content and metadata for the fire weather map page.
