la-ldaf/ldaf-site

.github/dependabot.yml
This adds a config file that will have Dependabot run on our `npm` packages weekly, and will open PRs that are automatically assigned to our engineering team. I set the commit prefix to `npm: ...` and it should automatically apply the `dependabot` and `dependencies` labels.
=> Set up automatic Dependabot version updates.

src/lib/components/Header/Header.svelte, src/lib/components/Header/Nav/Nav.svelte, src/lib/components/Header/Nav/NavItem.svelte, src/lib/components/Header/Nav/NavItem.test.ts, src/lib/components/Header/Nav/NavLink.svelte, src/lib/components/Header/Nav/NavMenu.svelte, src/lib/components/Header/Nav/index.ts, src/lib/components/Header/Nav/types.ts, src/lib/util/chunk.ts, src/stories/Header.stories.ts
- Makes `chunk` generic so that it doesn't infect variables with `any` types.
- Splits up `NavItemType` into `NavLinkType` and `NavMenuType`
- Splits up `NavItem` into `NavLink` and `NavMenu`
- Keeps "which, if any, menu is expanded" state in `Nav` component
- Uses events to signal expanding and closing the menu so that state can be kept in `Nav`
=> Review suggestions for #2

docs/decisions/sveltekit.md
Jira ticket: [LDAF-210](https://ldaf.atlassian.net/browse/LDAF-210)
Adds our first decision document to `/docs/decisions/` that explains our reasoning for and approach to choosing SvelteKit as our front-end framework for the site.
I think the main thing missing from this document is more references to outside sources. We obviously can't link to our internal research documents, but there were a handful of articles and blog posts that we passed around during the discovery process that ultimately helped us land on this decision. If you have any you'd like to include here, please let me know!
[LDAF-210]: https://ldaf.atlassian.net/browse/LDAF-210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LDAF-210 Add SvelteKit decision doc

.storybook/main.ts, package-lock.json, package.json, src/stories/Icon.stories.ts
Jira ticket: [LDAF-207](https://ldaf.atlassian.net/browse/LDAF-207)
Connecting our Storybook stories with Figma design files is a nice-to-have feature that could help to mitigate the two getting out of sync.
Following the latter half of [this Figma tutorial](https://help.figma.com/hc/en-us/articles/360045003494-Storybook-and-Figma#Embed_Figma_in_Storybook), I made the following changes:
- Installed the [storybook-addon-designs](https://github.com/storybookjs/addon-designs) plugin to add Figma support. We need to use the `beta` version since the plugin doesn't officially support Storybook 7 yet.
- "Configured" the plugin by adding it to the list of `addons` in `.storybook/main.ts`.
- Showed an example of how we can use this plugin by adding it to the `Icon` component stories. In Storybook …
=> LDAF-207 Set up Figma design file embeds within Storybook stories

src/app.scss, src/lib/components/Header/Header.scss, src/lib/components/Header/Header.svelte, src/lib/components/Link/Link.scss, src/lib/components/landingPage/Banner.scss, src/lib/components/landingPage/Footer.svelte, src/lib/components/landingPage/GraphicList.scss, src/lib/components/landingPage/GraphicList.svelte, src/lib/components/landingPage/Hero.scss, src/lib/components/landingPage/Hero.svelte, src/lib/components/landingPage/Identifier.svelte, src/routes/+page.svelte, src/routes/documentation/+page.svelte, src/routes/news/+page.svelte, src/routes/page.scss, src/stories/decorators/Prose.svelte, vite.config.ts
Jira ticket: [LDAF-216](https://ldaf.atlassian.net/browse/LDAF-216)
- Add sub-route that copies the [USWDS Documentation page template](https://designsystem.digital.gov/templates/documentation-page/#component-code)
- Use a single global import of USWDS
- Move shared components into top-level `+layout.svelte`
- Refactoring of styles, tests not needed yet for this change
[Gist summary of the different stylesheet sizes depending on import strategy   ](https://gist.github.com/hinzed1127/7baf4149a1a1e18d92e9b75fc3e9a907)
- This _is_ the alternate solution. See full list of considered options in the [original approach taken](https://github.com/adhocteam/ldaf/pull/64).
- Individual page sizes might be marginally larger, since a single top-level global import of USWDS will cause PurgeCSS to …
=> LDAF-216: Refactor USWDS dependency to single global import

static/robots.txt
Very quick PR that adds a `/robots.txt` that disallows all bots on all routes.
Created a Jira ticket to remind us to update this before launch: [LDAF-265](https://ldaf.atlassian.net/browse/LDAF-265)
[LDAF-265]: https://ldaf.atlassian.net/browse/LDAF-265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Stop robots from crawling the site until we're ready to launch

src/lib/components/Image/Image.svelte, src/lib/components/Image/types.ts, src/stories/Examples/LazyImageLoading/LazyImageLoading.mdx, src/stories/Examples/LazyImageLoading/LazyImageLoading.stories.ts, src/stories/Examples/LazyImageLoading/LazyImageLoading.svelte
- Organizes Storybook stories into folders
- Adds a demo of `IntersectionObserver` based lazy image loading to Storybook
=> Add lazy image loading Storybook example

src/lib/components/Button/Button.scss, src/stories/Button.stories.ts
Followup to #63.
- Adds explicit background and foreground color settings to `.usa-button.usa-button--unstyled`.
=> Button: fix unstyled button :hover and :active styles

.github/dependabot.yml
Not sure how I missed this in #41 but with the current config dependabot is running in the middle of the night, so I figured it would make more sense to use [`time`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduletime) and [`timezone`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduletimezone) to have it run in the morning, Central time. 
@Benaiah @hinzed1127 if you'd prefer, I could switch it to like 11am CT (9am PT) so that it's running during our core operating hours.
=> Set a reasonable time for dependabot to run.

.github/workflows/tests_and_reports.yml, .meta/index.html, src/routes/.build-info/+page.svelte
Jira ticket: LDAF-250
This is a follow-up to #168. Storybook currently takes a considerable amount of time to build and deploy, and since we're including it in the meta-site it's holding up the deploys of more immediately important reports. Moving it into its own Vercel app steamlines this; the meta-site can deploy much more quickly and since we're building and deploying Storybook all in the same step, we don't need to worry about creating an artifact (bypassing a lengthy upload / download process).
- Create a new Vercel app for Storybook: 
- App in Vercel: https://vercel.com/ldaf/storybook
- Production URL (showing Jekyll until we merge this): https://ldaf-storybook.vercel.app/
- Preview URL (where 188 is the PR number): https://storybook-188-ldaf.vercel.app/
- Create a new step in our …
=> Spin up separate Vercel app for Storybook

.eslintignore, .eslintrc.cjs, package-lock.json, package.json, src/lib/components/Header/Nav/Nav.server.ts, src/routes/[...dynamicRoute]/+page.server.ts, src/routes/[...dynamicRoute]/+page.svelte, src/routes/test-contentful-content/+page.server.ts
Depends on #150.
- Adds and configures `@graphql-eslint/eslint-plugin` to lint GraphQL queries declared with the `gql` tag or in `.graphql` or `.gql` files using the checked-in Contentful schema.
- Adds `graphql` and `graphql-tag`; uses `gql` on the server side to generate GraphQL queries that are linted by the ESLint plugin and then uses `graphql`'s `print` function to turn them back into strings (we'll do more interesting things with the parsed queries in the future).
- Names the GraphQL queries to get rid of a lint warning.
=> ESLint linting for GraphQL queries

package.json
Runs `npm run prebuild` before `npm run dev` starts. This prevents errors due to missing JSON "test" documents that we actually rely on in development when the Contentful connection isn't present.
=> Run prebuild before dev

.github/workflows/tests_and_reports.yml, e2e-tests/homepage.spec.ts
Always attempts to upload the artifact, even if the steps to create that artifact exited with an error. This fixes the issue where e2e test reports are not uploaded if any of the tests fail.
=> Attempt to upload artifacts even if the artifact creation step exited with an error

README.md, package-lock.json, package.json
Pretty straightforward; we're no longer using Chromatic due to rate limits, so we might as well remove the CLI (and stop getting dependabot updates for it). Afterwards I'll remove the API token from our secrets storage.
=> Remove Chromatic in favor of publishing Storybook to Vercel.

src/lib/services/contentful/schema.graphql, src/lib/services/contentful/schema.ts, src/routes/about/organization/[slug]/+page.server.ts, src/routes/about/organization/[slug]/__tests__/OfficePageTestContent.ts
In an effort to standardize references to Page Metadata entries, I renamed a bunch of fields in Contentful, which broke the current Office Page implementation. This is a quick fix to get it working again.
=> Quick fix to reflect change to Office Page model in Contentful.

src/lib/components/Header/Nav/Nav.server.ts, src/routes/(infoPages)/[topTierPage]/+page.server.ts, src/routes/(infoPages)/[topTierPage]/[...serviceGroupPage]/+page.server.ts, src/routes/(infoPages)/about/boards-commissions/[boardCommissionPage]/+page.server.ts, src/routes/(infoPages)/about/organization/[officePage]/+page.server.ts, src/routes/+layout.server.ts, src/routes/loadPageMetadataMap.ts
Jira ticket: [LDAF-350](https://ldaf.atlassian.net/browse/LDAF-350)
This PR is only focused on populating the main menu; there are no changes to the nav components or design (this will come later). Most of the changes are to one file, `src/lib/components/Header/Nav/Nav.server.ts`, where we're replacing our query for Draft Navigation content with one for Menu content. The main difference between these approaches is that Draft Navigation made editors explicitly provide all menus and menu children, whereas Menu just collects the Top Tier pages (so that we can order them appropriately) and from there we use the existing `PageMetadataMap` and the featured service groups on the Top Tier pages to construct the menus with very minimal editor interaction.
The structure for each menu (i.e. the …
=> LDAF-350 Populate main menu using page metadata.

src/lib/components/Header/Nav/__tests__/SecondaryNavTestContent.ts, src/routes/licensing-permits/+page.server.ts, src/routes/licensing-permits/+page.svelte
This is a very quick fix just to get the secondary nav updated. Should be straightforward but let me know if you have any questions!
=> Update secondary nav links and stub out 'Licensing and permits' page.

src/lib/components/Button/Button.scss, src/lib/components/Button/Button.svelte, src/lib/components/Button/buttonOptions.ts, src/lib/components/VideoCard/VideoCard.svelte, src/lib/components/VideoCard/index.ts, src/routes/(infoPages)/+layout.svelte, src/routes/(infoPages)/[topTierPage]/+page.server.ts, src/routes/(infoPages)/[topTierPage]/+page.svelte, src/routes/(infoPages)/[topTierPage]/[...serviceGroupPage]/+page.svelte, src/routes/(infoPages)/[topTierPage]/page.scss
Jira ticket: [LDAF-341](https://ldaf.atlassian.net/browse/LDAF-341)
Adds a rough implementation of the Top Tier pages, e.g. `/animals`, `/plants`, etc. Highlights are:
- Render the Top Tier pages with a hero image, title, subheading, description, video embed, and featured service cards.
- Update the base `(infoPages)` layout so that it supports `TopTier` pages as well (hero image, photo credit, and title appear above the two-column layout).
- The buttons on the Cards should vary depending on where they are in the order (first is `primary`, second is `secondary`, rest are `outline`).
- Some updates to the `Button` component:
- Render a `Link` instead of a `button` if `isLink` is set to `true`.
- Add a `secondary` variant (yellow).
- Add some messy support for coloring our SVG icons that …
=> LDAF-341 Create Top Tier pages

vite-plugin-import-as-bundle-string/index.ts
The irrelevant `@rollup/plugin-typescript` warnings we're getting when running `dev` are coming from one of our custom Vite plugins, so for now we can just suppress the one that's causing the most false positives (the implicit type warning). In the future we may want to suppress all warnings coming from the TS plugin, since it doesn't have the full view of the application (nor should it).
=> Suppress @rollup/plugin-typescript warnings on +page.server.ts files.

src/routes/licensing-permits/+page.svelte
@uxrebecca sent over some temporary content for us to put on the "Licensing and permits" page as a stop-gap until we can properly implement the aggregator page.
=> Hard code some content on the licensing and permits page for user testing.

src/lib/fragments/imageProps.ts, src/lib/util/chunks.ts, src/routes/(infoPages)/[topTierPage]/[...serviceGroupPage]/+page.server.ts, src/routes/test-contentful-content/+page.server.ts
- Splits up the service group page GraphQL query into separate queries for the base data and its children (service entries and groups).
- If more than 10 child service entries are present, chunks the queries into batches of 10 IDs at a time to avoid query complexity limits
=> Fix service group page by splitting query

src/lib/components/Card/Card.scss, src/lib/components/DotGovBanner/DotGovBanner.svelte, src/lib/components/Header/Logo/Logo.svelte, src/lib/components/Image/Image.scss, src/lib/components/Image/Image.svelte, src/lib/components/Image/types.ts, src/lib/constants/images.ts, src/lib/imageServices/contentful.ts, src/routes/(infoPages)/+layout.svelte, src/routes/(infoPages)/[topTierPage]/+page.server.ts, src/routes/(infoPages)/[topTierPage]/+page.svelte, src/routes/(infoPages)/layout.scss, src/routes/+page.svelte
- Uses `Image` for the hero image and card images on top tier pages
- Uses a very small version of the logo to display in the banner
- Resets the state of the Image component on src change, fixing the stale-image-on-client-side-navigation issue
- Some small fixes
=> Use Image component instead of img tags, reset image state on src change

src/routes/+layout.svelte
Not removing the full banner in case there's a need at some point, but removing it from the actual header.
=> Remove dot-gov banner

src/lib/components/Header/Header.svelte, src/lib/components/Image/Image.svelte, src/stories/CardView.svelte
- Adds `max-width` and `max-height` to the image container if the image size type is not full bleed.
- Makes "static" on option for the "sizeType" of an image, which sets its `sizes` attribute to its static size (but _not_ its srcset attribute, so multiple DPI options
=> Don't upscale content images

src/lib/components/Button/Button.svelte, src/lib/components/Header/Nav/NavMenu.svelte
On Safari, menus in the header do not close when the user clicks away or navigates to a new page. This is due to Safari not automatically applying `focus` to `<button>` and `<a>` elements on click (and thus our `focusout` event is not triggered when the user clicks away from a menu or when the user navigates).
1. Open up [new.ldaf.la.gov]() in Safari.
2. Open one of the menus.
3. Confirm that clicking outside the menu does not close it.
4. Confirm that navigating to a different page does not close it.
Add two additional checks for Safari that should be redundant for other browsers:
1. Create an event listener on the `<body>` element that will check where a user clicked (technically `mousedown`), and close an opened menu if the target was outside the menu.
2. Always close an opened menu …
=> Fix a bug in the main menu in Safari

src/lib/components/VideoCard/VideoCard.svelte, src/lib/components/YoutubeSubscribeLink/YoutubeSubscribeLink.svelte, src/lib/components/YoutubeSubscribeLink/index.ts
Uses a styled link resembling the YouTube subscribe button to replace the embedded subscribe button and avoid all the extra JS it was loading. This also fixes the errors that were happening when navigating around the site if a `VideoCard` had _ever_ been loaded.
=> Reimplement youtube subscribe button, avoiding loading google js

e2e-tests/header.spec.ts, src/routes/(infoPages)/about/news/+page.server.ts, src/routes/(infoPages)/about/news/+page.svelte
Quick fix, as part of this I also unpublished the appropriate entries in Contentful:
* Page Details for News - https://app.contentful.com/spaces/pc5e1rlgfrov/entries/7uRzUfPjJoNjTXlVCcjOIi
* Page Details for an article with News as the parent - https://app.contentful.com/spaces/pc5e1rlgfrov/environments/master/entries/4I50gHKAiy0QkxMUEJmcmT
* Menu Item in Footer for News - https://app.contentful.com/spaces/pc5e1rlgfrov/environments/master/entries/3MouxaFvLV8EKtbQmU18la
=> Disable the news route as its not implemented yet.

src/lib/components/ContentfulRichText/ContentfulRichText.svelte
- Remove random IDs from `each` block in `ContentfulRichText` - we shouldn't be using random IDs in real code
=> Don't use random component ID outside of tests/storybook

src/routes/api/v1/algolia/+server.ts
Discussed during our "think tank" meeting, we need to make sure we're not linking to pages that don't exist, and there's not much use in linking to the home page.
=> Filter out the home page and null URLs from search.

src/hooks.server.ts, src/lib/services/server/kv/index.ts
- Cache the KV client to avoid creating and connecting a new Redis client every request, which leaks file descriptors.
It's rather difficult to test if this is actually working or not, either manually or automatically. Existing tests pass, and I'm working on verifying that we're not leaking FDs.
Update: I was able to reproduce the problem locally and verify the fix by checking the open file descriptor list in Activity Monitor.
=> Stop leaking a redis client connection descriptor every request

src/lib/components/Image/Image.svelte
- Changes `preserveAspectRatio` default to depend on the given `sizeType`.
- Makes `"card"` sized images not preserve aspect ratio.
=> Don't preserve aspect ratio of card images

src/app.html
Sets a meta tag with the theme color. This is the color used by browsers (primarily mobile browsers) to theme the address bar area. Matching it with the background color of the header should make it a smooth transition.
=> Set meta tag with theme color

.github/workflows/tests_and_reports.yml, .gitignore
When running Lighthouse reports, send an extra header to let Vercel know to disable preview comments.  Without that extra cruft, the reports on preview URLs should more closely reflect how the reports will perform on production.
Docs: https://vercel.com/docs/workflow-collaboration/comments/specialized-usage#disable-comments-temporarily
To test, open up the Lighthouse reports and view an HTML report (e.g. [homepage on mobile](https://meta-site-402-ldaf.vercel.app/lighthouse/mobile/ldaf-lunz59dzh-ldaf_vercel_app_.report.html)). You should no longer see the Vercel toolbar at the bottom of the page in the report's screenshot.
=> Disable the Vercel toolbar when running Lighthouse reports.

src/lib/components/VideoCard/VideoCard.svelte
I was using templating in a non-template string 🤦. I've also adjusted the static desktop sizes to be more accurate.
=> Fix `sizes` attribute of youtube thumbnail

src/lib/vitals.ts, src/routes/+layout.server.ts
We're currently sending data to Speed Insights even in development and preview settings.
=> Only send speed insights in production; load `web-vitals` on demand

package-lock.json, package.json, src/lib/constants/date.ts, src/lib/util/dates.test.ts, src/lib/util/dates.ts, src/routes/(infoPages)/about/events/event/[dateAndSlug]/+page.server.ts, src/routes/(infoPages)/about/events/shared.server.ts
Jira ticket: [TICKET_NUMBER](URL)
- Does all event calculations using the start and end of day _in Louisiana_, not the current timezone wherever the server is running.
- Filters out past events from event aggregation page
=> Make all event dates relative to Louisiana timezone; filter events aggregation page to present+future events

.github/workflows/tests_and_reports.yml
This is only really necessary in situations like we have today where we have many changes being merged and a lot of open PRs that are all redeploying previews to Vercel at the same time.
=> Increase timeout for Lighthouse to wait for Vercel preview deployment.

src/lib/components/Accordion/Accordion.svelte, src/lib/components/Accordion/AccordionItem.svelte, src/lib/components/Accordion/context.ts, src/routes/(infoPages)/[topTierPage]/[...serviceGroupPage]/+page.svelte
Jira ticket: [LDAF-371](https://ldaf.atlassian.net/browse/LDAF-371)
- Adds an `each` key that is the accordion item ID when rendering child accordion components. This fixes a bug where the state and event handlers were being inappropriately preserved after page navigation, leading to an accordion item that is open by default (instead of closed) and takes two clicks to close (because the event handler is stale).
- Slightly refactors `Accordion`.
Right now it's still not perfect because the expandedItems record is still sticking around after navigation, it's just not causing problems because we never use accordion items with the same ID on separate pages.
[LDAF-371]: https://ldaf.atlassian.net/browse/LDAF-371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …
=> Fix stale accordion-expanded state when navigating between pages

src/routes/(infoPages)/about/organization/[officePage]/+page.server.ts, src/routes/(infoPages)/about/organization/[officePage]/+page.svelte
This issue came up from @uxrebecca's [post in Slack](https://adhoc.slack.com/archives/C03QPK0E2UU/p1693338707360349); when we made the updates to support links and images in rich text fields we missed the Office Pages. This PR refactors the query for the data to be more inline with our other queries (mostly stolen from the Core Content page query) and adds the support for links and images.
=> Slight refactor to Office Page query. Add support for links and images in Office Page rich text.

src/app.scss, src/lib/components/ContentfulRichText/context.ts, src/lib/components/ContentfulRichText/types.ts, src/lib/components/Tag/Tag.svelte, src/lib/components/Tag/Tag.test.ts, src/lib/components/Tag/index.ts, src/lib/util/dates.ts, src/routes/(infoPages)/about/events/+page.svelte, src/routes/(infoPages)/about/events/page/[page]/+page.server.ts, src/routes/(infoPages)/about/events/shared.server.ts, src/routes/(infoPages)/about/news/+page.server.ts, src/routes/(infoPages)/about/news/+page.svelte, src/routes/(infoPages)/about/news/News.svelte, src/routes/(infoPages)/about/news/NewsEntrySnippet.svelte, src/routes/(infoPages)/about/news/__tests__/newsTestContent.ts, src/routes/(infoPages)/about/news/article/[slug]/+page.server.ts, src/routes/(infoPages)/about/news/article/[slug]/+page.svelte, src/routes/(infoPages)/about/news/article/[slug]/page.scss, src/routes/(infoPages)/about/news/page.scss, src/routes/(infoPages)/about/news/page/[page]/+page.server.ts, src/routes/(infoPages)/about/news/page/[page]/+page.svelte, src/routes/(infoPages)/about/news/shared.server.ts, src/routes/(infoPages)/layout.scss, src/stories/Tag.stories.ts
Jira ticket: [LDAF-362](https://ldaf.atlassian.net/browse/LDAF-362)
- Adds pages for news, heavily copied from work done in #364 (we have a follow-up ticket to cut down on the repetition).
- Adds a `NewEntrySnippet` component for showing only some data for a news entry, for use on the aggregation pages or as a related news entry. 
- Adds another `date` utility for converting a Contentful UTC date without a timestamp to a date string, e.g. `2023-08-31T00:00:00.000Z` converts to `August 31, 2023` when using `getUTC*` methods (if we don't use the `getUTC*` methods we would get `August 30, 2023` because of the timezone difference).
- Adds a simple `Tag` component with a test and story.
- Fixes default paragraph width within container elements with the `usa-prose` class.
There are two …
=> Implement news aggregation page and individual news article and press release pages

src/lib/components/Date/Date.scss, src/lib/components/Date/Date.svelte, src/routes/(infoPages)/about/events/Event.svelte, src/routes/(infoPages)/about/news/NewsEntrySnippet.svelte, src/routes/+page.server.ts, src/routes/+page.svelte, src/routes/__tests__/homePageTestContent.ts, src/routes/page.scss
Jira ticket: [LDAF-402](https://ldaf.atlassian.net/browse/LDAF-402)
This is pretty similar to #462; we want to display news and events on the homepage but in a slightly more compact style.
- As part of the homepage query, also request the 4 most recent news entries and the next 4 upcoming events, and render them on the homepage between "Popular resources" and "From the commissioner" sections.
- Adjust lots of spacing on the homepage to more closely match mocks.
- Allow variations on News and Events components to render them slightly differently on the homepage.
- Make some minor adjustments to the styling of the Event component (color, size, month capitalization)
See self-review.
[LDAF-402]: https://ldaf.atlassian.net/browse/LDAF-402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
=> [LDAF-402] Render latest news and upcoming events on the Home Page

src/app.html, src/app.scss, src/lib/components/Alert/Alert.scss, src/lib/components/AnnouncementBanner/AnnouncementBanner.scss, src/lib/components/Button/Button.scss, src/lib/components/ContentfulRichText/nodes/Hyperlink.svelte, src/lib/components/Footer/Footer.scss, src/lib/components/Footer/Footer.svelte, src/lib/components/Header/Header.scss, src/lib/components/Link/Link.scss, src/lib/components/Pagination/Pagination.scss, src/lib/components/VideoCard/VideoCard.scss, src/lib/components/YoutubeSubscribeLink/YoutubeSubscribeLink.scss, src/routes/(infoPages)/[topTierPage]/+page.svelte, src/routes/(infoPages)/[topTierPage]/[...serviceGroupPage]/+page.svelte, src/routes/+layout.svelte, src/routes/+page.svelte, src/routes/page.scss, src/routes/search/search-page.scss, src/stories/Alert.stories.ts, src/stories/Button.stories.ts, src/variables.scss
Jira ticket: [LDAF-427](https://ldaf.atlassian.net/browse/LDAF-427)
This is a replacement of #468; you don't necessarily need to look at the code on that PR, but the PR description provides some context.
Previously I had run into issues with using the USWDS theming settings because there are some settings that must take tokens (I was under the impression that all setings had to take tokens). I've documented this relatively well in `src/app.scss,` but basically there are two different types of settings: those where you can provide custom colors (we're using hex color variables), and those where you must use tokens. Thankfully in most cases we can use tokens that we're able to customize, but there are some outliers (in this PR, the main one is the visited link color).
- Sets all applicable …
=> [LDAF-427] Update link and button colors across site by using USWDS theming settings

src/routes/(infoPages)/about/events/+page.svelte, src/routes/(infoPages)/about/events/shared.server.ts
=> Show an empty state for events, not the 404 page, when events.length is 0

src/lib/fragments/entryProps.ts
This fixes the `Cannot query field "imageCategory" on type "ImageWrapper".` error that was occurring after the content model was changed
=> Remove unused properties on ImageWrapper query

src/routes/(infoPages)/[topTierPage]/+page.server.ts
I discovered this in the process of working on [LDAF-433](https://ldaf.atlassian.net/browse/LDAF-433). We already display the 5 most recent tagged events on top tier pages; this just displays them in preview.
[LDAF-433]: https://ldaf.atlassian.net/browse/LDAF-433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Enable viewing preview content for tagged events on top tier pages

src/hooks.server.ts, src/hooks/server/handleBadActors.ts
Before we perform any load logic, we check the user agent of the request and give them an error if we know they're up to no good. More details are available in the in-code comments.
Open up your HTTP-request-tool of choice and send a request to any URL on the site (either to your local or to the Vercel preview deployment) with the `User-Agent` header set to:
```
FeedFetcher-Google; (+http://www.google.com/feedfetcher.html)
```
All requests (besides to static assets such as `/robots.txt` and `/favicon.ico`) should result in a `419 Never Gonna Give You Up` error. This is not a real error code, but these requests don't deserve a real error code (in all seriousness, I can change this to a `403 Forbidden` if we want to be proper).
=> Block bad actors by immediately responding with an HTTP error code.

package-lock.json, package.json, src/routes/api/v1/fire-weather/+server.ts
- Adds an API route at `/api/v1/fire-weather`
- Presently just parses out an CSV file and returns it as JSON; will get updated to get added to the Vercel KV store
I tested this locally with the [following script](https://gist.github.com/hinzed1127/4f51bef0853f6767fb7d7cf8912dffb1). It's intentionally very basic right for now
- Right now is requiring we integrate with LDAF's IIS FTP server. TBD on how integrating a node script within that goes
- TBD on how easy the KV integration is
=> Add API route to process fire data CSV

src/lib/components/Event/Event.svelte, src/lib/components/Event/index.ts, src/lib/components/NewsEntry/NewsEntry.svelte, src/lib/components/NewsEntry/index.ts, src/lib/fragments/entryProps.ts, src/lib/services/server/contentful/schema.graphql, src/lib/services/server/contentful/schema.ts, src/routes/(infoPages)/[topTierPage]/+page.server.ts, src/routes/(infoPages)/[topTierPage]/+page.svelte, src/routes/(infoPages)/[topTierPage]/[...serviceGroupPage]/+page.server.ts, src/routes/(infoPages)/[topTierPage]/[...serviceGroupPage]/+page.svelte, src/routes/(infoPages)/about/events/+page.svelte, src/routes/(infoPages)/about/news/+page.svelte, src/routes/(infoPages)/about/news/article/[slug]/+page.server.ts, src/routes/(infoPages)/about/news/article/[slug]/+page.svelte, src/routes/+page.svelte
- add entity relationship for recent news and events to core content page
- add entity relationship for recent news and events to service entry page
Top Tier:
Currently, the tagged content overrides the entity relationships if the tagged content exists. This could be confusing for editors until all the tagged content is removed.
<!-- If you plan on leaving a self-review, note that here. >
=> Add Recent News and Events Entity relationships to TopTier and ServiceEntry

src/lib/services/server/contentful/schema.graphql, src/lib/services/server/contentful/schema.ts, src/routes/(infoPages)/about/organization/[officePage]/__tests__/OfficePageTestContent.ts
Ran `npm run gen-schema` to get the latest updates (including a new built-in field, `concepts`), and then needed to update some test data for the Office Pages (since these are using an outdated mechanism for handling Contentful data) to get type checks passing.
=> [No Issue] Update schema after latest changes to Contentful (both built-ins and our content model changes).

src/lib/services/server/contentful/schema.graphql, src/lib/services/server/contentful/schema.ts, src/routes/(infoPages)/land/fire/safety/fire-danger-map/+page.server.ts, src/routes/(infoPages)/land/fire/safety/fire-danger-map/+page.svelte
- Integrates Contentful with the Fire Weather Map
- Added a [single-use content type](https://app.contentful.com/spaces/pc5e1rlgfrov/content_types/fireDangerMap/fields) for that page.
- [Content content using that content type](https://app.contentful.com/spaces/pc5e1rlgfrov/entries/7fiQCwkywcWi7lBy0dayqd?focusedField=title)
Notice that it gets included in the navigation side bar:
Description rich text served from Contentful:
- In theory, we could use a core content page, since this is a subset of those properties, but I think it's better to explicitly restrict it to just the description alongside the map.
=> Fire Weather Map Updates

src/routes/api/v1/search-index/+server.ts, src/routes/api/v1/search-index/news-and-events/+server.ts, src/routes/api/v1/search-index/service-entries/+server.ts, src/routes/api/v1/search-index/types.ts
There's enough here that I wanted to separate it out into a side-PR before merging everything.
On a high level, this: 
- breaks out news and events updates into their own API endpoint and contentful webhook
- reverts some of the mapping in the original algolia endpoint to make sure `pageMetadata` records don't get accidentally undefined
=> Refactor news and events
